### PR TITLE
maintainers: Update email for dcantah

### PR DESCRIPTION
**Pull request by dcantah**

### CODE REVIEW

**Comment by dcantah** [comment]
Ah, CI should be fixed with this https://github.com/containerd/project/pull/93

**Review by estesp — APPROVED** [review]
LGTM

**Review by samuelkarp — APPROVED** [review]

**Comment by dcantah** [comment]
Updated to sign off this change with the email I'm swapping to 😆

**Review by AkihiroSuda — APPROVED** [review]

**Comment by AkihiroSuda** [comment]
CI failure is unrelated, merging

**Pull request merged**
