### PR TITLE
security doc: Update options to report vulnerability

### PR DESCRIPTION
**Pull request by dcantah**
Add in a new blurb about reporting an issue on Github directly and include some images to help guide to the right spot on a given repo.

### CODE REVIEW

**Comment by dcantah** [comment]
Thanks for the suggestion, this feels like the right spot @AkihiroSuda

**Comment by samuelkarp** [comment]
> d57aab2 - FAIL - has whitespace errors. See `git show --check d57aab2cffe1ad59cc20f05b80a43de7d1f50002`.

There's some trailing whitespace in your commit message.

**Comment by dcantah** [comment]
Rats, thought I fixed this

**Review by samuelkarp — APPROVED** [review]

**Review by estesp — APPROVED** [review]
LGTM

**Review by AkihiroSuda — APPROVED** [review]

**Review by dmcgowan — APPROVED** [review]

**Pull request merged**
