### PR TITLE
Remove Kenfe-Mickael Laventure from maintainers list

### PR DESCRIPTION
**Pull request by mlaventure**
Unfortunately, despite my best effort, I have been unable to go back
into being a productive contributor to containerd and even less so to
fulfill my role as a maintainer. As such, I think it is time for me to
remove myself from the list. I'll still lurk around though :eyes:

Signed-off-by: Kenfe-Mickael Laventure <mickael.laventure@gmail.com>

### CODE REVIEW

**Comment by estesp** [comment]
I know I miss working with you but totally understand it isn't always possible to stay active depending on job role/focus. I truly hope you are doing well!

**Review by estesp — APPROVED** [review]

**Comment by dmcgowan** [comment]
Sad to see one of the original creators of containerd step down! Your impact on the project will be long lasting. I appreciate you taking the time to weigh in on the important project votes despite having moved on to other adventures. I know it isn't my call to reject this change, but from my perspective you have been fulfilling the role as needed by offering your unique insight to the project and helping reach quorum on votes. I hope you can reconsider remaining on in the reviewer role to keep your LGTM weight when you lurk on something of interest.

**Review by mikebrow — APPROVED** [review]
LGTM

**Comment by dims** [comment]
LGTM

thanks for all your work @mlaventure

**Comment by mlaventure** [comment]
> Sad to see one of the original creators of containerd step down! Your impact on the project will be long lasting. I appreciate you taking the time to weigh in on the important project votes despite having moved on to other adventures. I know it isn't my call to reject this change, but from my perspective you have been fulfilling the role as needed by offering your unique insight to the project and helping reach quorum on votes. I hope you can reconsider remaining on in the reviewer role to keep your LGTM weight when you lurk on something of interest.

I appreciate it, thanks :heart: . But, I don't think it'd be fair for my voice to have too much of a say given how detached I found myself to be currently. But if I see something, I'll say something :)

**Pull request merged**
