### PR TITLE
Add Justin Terry as a Reviewer

### PR DESCRIPTION
**Pull request by crosbymichael**
Justin has been contributing to both the core containerd daemon and CRI
code getting Windows working.

The code has been inline with the project's goals and design to make a
very simple and robust implementation.

His reviews on other runtime and storage related code has been valuable
and has been working consistently on the project for the past few
months.

cc @jterry75

Signed-off-by: Michael Crosby <crosbymichael@gmail.com>

### CODE REVIEW

**Comment by dmcgowan** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Comment by jhowardmsft** [comment]
LGTM 🎈

**Comment by dmcgowan** [comment]
> The reviewer role has the same process but only requires 33% of current maintainers. 

5/14, merging

**Pull request merged**
