### PR TITLE
Promote Justin Terry (@jterry75) from reviewer to maintainer

### PR DESCRIPTION
**Pull request by jhowardmsft**
Signed-off-by: John Howard <jhoward@microsoft.com>

Justin has been doing some extremely valuable work in the containerd repos for many months now to get both runtime and snapshotters for containerd ported to Windows. I think it's time we recognize that work, his ongoing contributions, and engineering excellence by promoting him from a project reviewer to maintainer.

Governance requires a LGTM from at least 66% (or 8) of the current 12 maintainers (https://github.com/containerd/project/blob/master/GOVERNANCE.md#adding-maintainers)
- [x] @AkihiroSuda
- [x] @crosbymichael
- [x] @dmcgowan
- [x] @estesp
- [x] @jhowardmsft
- [x] @mlaventure
- [ ] @stevvooe
- [x] @abhi
- [x] @dchen1107
- [x] @Random-Liu
- [x] @mikebrow
- [ ] @yujuhong

cc Existing reviewers FYI: @dqminh @hqhq @yanxuean @miaoyq @ehazlett @fuweid @Ace-Tang. And, of course, @jterry75

### CODE REVIEW

**Comment by dmcgowan** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Comment by Random-Liu** [comment]
LGTM

**Comment by jterry75** [comment]
Wahoo!! Thanks everyone!

**Comment by dchen1107** [comment]
LGTM

**Comment by mikebrow** [comment]
LGTM

**Pull request merged**
