### PR TITLE
Support Go Modules

### PR DESCRIPTION
**Pull request by SamWhited**
Attempting to support modules for containerd projects. Specifically this PR adds a `go.mod` file for this repo and updates the vendor validation script to support go modules alongside `vndr` by checking for the presence of `vendor.conf` and using `vndr` if it exists or `go mod vendor` if it does not.

### CODE REVIEW

**Comment by estesp** [comment]
Sorry that we hadn't removed the `release-tool` from this repo yet; I just opened a PR #27 to correct this. Can you move this work to the new [`release-tool` repo](https://github.com/containerd/release-tool)?

**Comment by SamWhited** [comment]
Sure thing, as soon as your PR is merged I'll remove everything from this PR except the validation script fix, and then after that's merged I can update the `release-tools` repo to use Go Modules.

**Comment by SamWhited** [comment]
Done, PTAL.

**Comment by dmcgowan** [comment]
This was the previous method used in some PRs and we suggested adding here #26

**Comment by SamWhited** [comment]
Adding tidy sounds good, but we probably don't want to check the value of GO111MODULE because "on" will be the default value when Go 1.14 is released and if it's defaulting to on it still won't show up in `go env GO111MODULE`. It could also be set to auto and we could be outside of GOPATH in which case we may still want to use module mode. Since this is repo specific I don't think we can depend on an environment variable, but the go.mod file being present is probably a good indicator that we intended to use modules with this repo.

**Comment by estesp** [comment]
This method seems to make sense to me, and helps have an easy "switch" for transition--when the `vendor.conf` is removed from a repo, you get automatic enablement of the `go mod` checks.

**Comment by kzys** [comment]
I thought we would have a transition period where we still use `vndr` but make sure `go mod` is working. Dependencies like [gotest.tools should be updated](https://github.com/gotestyourself/gotest.tools/commit/172219a9d5ee3d999469401935c4714c72c85420) before adding go.mod.

If we don't have the transition period, we can just use either `vndr` or `go mod`.

**Comment by SamWhited** [comment]
A transition period seems like you'd just wind up with the vendor.conf and go.mod being out of sync somehow, then when you switch over fully to go.mod you accidentally downgrade a dependency. You would possibly also want to add a test that always checked that they were in sync on each PR.

This seems like a lot of work to me instead of just upgrading repo-by-repo to go.mod.

**Comment by dmcgowan** [comment]
Sure, let's try this approach, it seems very reasonable and requires no extra configuration from the caller.

LGTM

**Pull request merged**
