### PR TITLE
Add Brian Goff as reviewer

### PR DESCRIPTION
**Pull request by dmcgowan**
Brian has been very helpful in reviewing code and contributing to containerd. This change just makes what he has already been doing official.

5 maintainer LGTM required (1/3) + new reviewer

- [x] @cpuguy83 (required)
- [x] @AkihiroSuda
- [x] @crosbymichael
- [x] @dmcgowan
- [x] @estesp
- [ ] @jhowardmsft
- [x] @jterry75
- [x] @mlaventure
- [x] @stevvooe
- [ ] @abhi
- [x] @dchen1107
- [x] @Random-Liu
- [x] @mikebrow
- [x] @yujuhong
- [x] @fuweid

### CODE REVIEW

**Comment by mikebrow** [comment]
LGTM, cool another trek fan

**Comment by stevvooe** [comment]
LGTM

**Comment by Random-Liu** [comment]
LGTM

**Comment by mikebrow** [comment]
LGTM

**Comment by AkihiroSuda** [comment]
ping @containerd/containerd-maintainers

**Comment by AkihiroSuda** [comment]
ping @containerd/containerd-maintainers

**Comment by crosbymichael** [comment]
LGTM

**Comment by AkihiroSuda** [comment]
@estesp @jhowardmsft @abhi @dchen1107 @yujuhong PTAL^^

**Comment by dchen1107** [comment]
LGTM

**Comment by yujuhong** [comment]
LGTM

**Pull request merged**
